version: '3.11'
services:
  frontend:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8084:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 15s