name: Smoketest

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: 18.x

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Verify formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Verify formatting
        run: yarn format:check

  build:
    name: Build site
    runs-on: ubuntu-latest

    needs: [formatting]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Restore Gatsby cache
        uses: actions/cache@v3
        id: gatsbyCache
        with:
          path: ./.cache
          key: ${{ runner.os }}-gatsby-cache-${{ secrets.CACHE_VERSION }}-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-${{ secrets.CACHE_VERSION }}-

      - name: Build site
        run: yarn build:ci
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
